apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{.APP_ID}}"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: {{.REPO}}
    repoURL: https://github.com/liehart/helm-chart.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: registry.idcix.net/idcix/{{.REPO}}
          tag: "{{.IMAGE_TAG}}"
        ingress:
          host: "{{.APP_ID}}.idcix.net"
        imagePullSecrets:
        - name: regcred
      version: v3
  destination:
    namespace: "{{.APP_ID}}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true