apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "image-compress-staging"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: "image-compress"
    repoURL: "https://github.com/liehart/helm-chart.git"
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: "registry.pipeline.dev.vriyas.com/private/image-compress"
          tag: "90f05ad071c01db443d8feeed85caa759ddae8fb"
        ingress:
          host: "image-compress-staging.pipeline.dev.vriyas.com"
      version: v3
  destination:
    namespace: "image-compress-staging"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true