apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "image-compress-staging-ea47933e"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    path: "image-compress"
    repoURL: "https://github.com/liehart/helm-chart.git"
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: "registry.pipeline.dev.vriyas.com/private/image-compress"
          tag: "ea47933e70197189a7e49a8b2b7b9b16a551718b"
        ingress:
          host: "image-compress-staging-ea47933e.pipeline.dev.vriyas.com"
      version: v3
  destination:
    namespace: "image-compress-staging-ea47933e"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true