---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pr-12-main-aubrieta
  namespace: argocd
spec:
  destination:
    namespace: pr-12-main-aubrieta
    server: https://kubernetes.default.svc
  project: previews
  source:
    helm:
      values: |
        image:
          tag: "84970ce6e9e505db8ce3beda4b05c26731eeee8a"
        ingress:
          host: "pr-12-main-aubrieta.idcix.net"
      version: v3
    path: helm
    repoURL: https://github.com/liehart/aubrieta.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
